// Bundled Lucide icon map. Every icon renders from the local bundle —
// no runtime CDN fetches, so lists of icons paint in a single pass.
// Unknown names (e.g. hand-typed category icons) fall back to CircleQuestionMark.
import type { LucideIcon } from "lucide-react"
import {
	ArrowDown as ArrowDownIcon,
	ArrowLeft as ArrowLeftIcon,
	ArrowLeftRight as ArrowLeftRightIcon,
	ArrowRight as ArrowRightIcon,
	ArrowUpRight as ArrowUpRightIcon,
	BadgeDollarSign as BadgeDollarSignIcon,
	Bike as BikeIcon,
	Binoculars as BinocularsIcon,
	BookOpen as BookOpenIcon,
	Brain as BrainIcon,
	CalendarClock as CalendarClockIcon,
	CalendarDays as CalendarDaysIcon,
	Calendar as CalendarIcon,
	CalendarRange as CalendarRangeIcon,
	CardSim as CardSimIcon,
	CarFront as CarFrontIcon,
	CarTaxiFront as CarTaxiFrontIcon,
	ChartArea as ChartAreaIcon,
	ChartCandlestick as ChartCandlestickIcon,
	ChartNoAxesCombined as ChartNoAxesCombinedIcon,
	ChevronDown as ChevronDownIcon,
	ChevronLeft as ChevronLeftIcon,
	ChevronRight as ChevronRightIcon,
	CircleAlert as CircleAlertIcon,
	CircleCheckBig as CircleCheckBigIcon,
	CircleDashed as CircleDashedIcon,
	CircleDollarSign as CircleDollarSignIcon,
	CircleGauge as CircleGaugeIcon,
	Club as ClubIcon,
	Coffee as CoffeeIcon,
	Cpu as CpuIcon,
	CreditCard as CreditCardIcon,
	CupSoda as CupSodaIcon,
	Database as DatabaseIcon,
	DollarSign as DollarSignIcon,
	Download as DownloadIcon,
	File as FileIcon,
	FileJson as FileJsonIcon,
	Flame as FlameIcon,
	FolderCode as FolderCodeIcon,
	Footprints as FootprintsIcon,
	Gauge as GaugeIcon,
	Gift as GiftIcon,
	HandCoins as HandCoinsIcon,
	HatGlasses as HatGlassesIcon,
	Heart as HeartIcon,
	HeartPulse as HeartPulseIcon,
	History as HistoryIcon,
	Hospital as HospitalIcon,
	House as HouseIcon,
	IceCreamBowl as IceCreamBowlIcon,
	IdCard as IdCardIcon,
	Import as ImportIcon,
	Inbox as InboxIcon,
	Info as InfoIcon,
	Lamp as LampIcon,
	Landmark as LandmarkIcon,
	Link2 as Link2Icon,
	Link2Off as Link2OffIcon,
	Link as LinkIcon,
	ListFilter as ListFilterIcon,
	ListX as ListXIcon,
	LoaderCircle as LoaderCircleIcon,
	MirrorRound as MirrorRoundIcon,
	MonitorSmartphone as MonitorSmartphoneIcon,
	Navigation as NavigationIcon,
	PartyPopper as PartyPopperIcon,
	Pencil as PencilIcon,
	Percent as PercentIcon,
	PiggyBank as PiggyBankIcon,
	Pill as PillIcon,
	Plane as PlaneIcon,
	Plus as PlusIcon,
	ReceiptText as ReceiptTextIcon,
	Replace as ReplaceIcon,
	RotateCcw as RotateCcwIcon,
	Route as RouteIcon,
	Sandwich as SandwichIcon,
	Scale as ScaleIcon,
	Scissors as ScissorsIcon,
	SearchX as SearchXIcon,
	Shirt as ShirtIcon,
	ShoppingBag as ShoppingBagIcon,
	Soup as SoupIcon,
	Sparkles as SparklesIcon,
	Tag as TagIcon,
	Tags as TagsIcon,
	Ticket as TicketIcon,
	Toolbox as ToolboxIcon,
	TowelRack as TowelRackIcon,
	TrainFront as TrainFrontIcon,
	Trash2 as Trash2Icon,
	Trash as TrashIcon,
	TriangleAlert as TriangleAlertIcon,
	Upload as UploadIcon,
	Utensils as UtensilsIcon,
	WalletCards as WalletCardsIcon,
	Warehouse as WarehouseIcon,
	Wine as WineIcon,
	Wrench as WrenchIcon,
	X as XIcon,
} from "lucide-react"

export const FALLBACK_ICON_NAME = "circle-question-mark"

export const ICONS: Record<string, LucideIcon> = {
	"arrow-down": ArrowDownIcon,
	"arrow-left": ArrowLeftIcon,
	"arrow-left-right": ArrowLeftRightIcon,
	"arrow-right": ArrowRightIcon,
	"arrow-up-right": ArrowUpRightIcon,
	"badge-dollar-sign": BadgeDollarSignIcon,
	bike: BikeIcon,
	binoculars: BinocularsIcon,
	"book-open": BookOpenIcon,
	brain: BrainIcon,
	calendar: CalendarIcon,
	"calendar-clock": CalendarClockIcon,
	"calendar-days": CalendarDaysIcon,
	"calendar-range": CalendarRangeIcon,
	"car-front": CarFrontIcon,
	"car-taxi-front": CarTaxiFrontIcon,
	"card-sim": CardSimIcon,
	"chart-area": ChartAreaIcon,
	"chart-candlestick": ChartCandlestickIcon,
	"chart-no-axes-combined": ChartNoAxesCombinedIcon,
	"chevron-down": ChevronDownIcon,
	"chevron-left": ChevronLeftIcon,
	"chevron-right": ChevronRightIcon,
	"circle-alert": CircleAlertIcon,
	"circle-check-big": CircleCheckBigIcon,
	"circle-dashed": CircleDashedIcon,
	"circle-dollar-sign": CircleDollarSignIcon,
	"circle-gauge": CircleGaugeIcon,
	club: ClubIcon,
	coffee: CoffeeIcon,
	cpu: CpuIcon,
	"credit-card": CreditCardIcon,
	"cup-soda": CupSodaIcon,
	database: DatabaseIcon,
	"dollar-sign": DollarSignIcon,
	download: DownloadIcon,
	file: FileIcon,
	"file-json": FileJsonIcon,
	flame: FlameIcon,
	"folder-code": FolderCodeIcon,
	footprints: FootprintsIcon,
	gauge: GaugeIcon,
	gift: GiftIcon,
	"hand-coins": HandCoinsIcon,
	"hat-glasses": HatGlassesIcon,
	heart: HeartIcon,
	"heart-pulse": HeartPulseIcon,
	history: HistoryIcon,
	hospital: HospitalIcon,
	house: HouseIcon,
	"ice-cream-bowl": IceCreamBowlIcon,
	"id-card": IdCardIcon,
	import: ImportIcon,
	inbox: InboxIcon,
	info: InfoIcon,
	lamp: LampIcon,
	landmark: LandmarkIcon,
	link: LinkIcon,
	"link-2": Link2Icon,
	"link-2-off": Link2OffIcon,
	"list-filter": ListFilterIcon,
	"list-filter-x": ListXIcon,
	"loader-circle": LoaderCircleIcon,
	"mirror-round": MirrorRoundIcon,
	"monitor-smartphone": MonitorSmartphoneIcon,
	navigation: NavigationIcon,
	"party-popper": PartyPopperIcon,
	pencil: PencilIcon,
	percent: PercentIcon,
	"piggy-bank": PiggyBankIcon,
	pill: PillIcon,
	plane: PlaneIcon,
	plus: PlusIcon,
	"receipt-text": ReceiptTextIcon,
	replace: ReplaceIcon,
	"rotate-ccw": RotateCcwIcon,
	route: RouteIcon,
	sandwich: SandwichIcon,
	scale: ScaleIcon,
	scissors: ScissorsIcon,
	"search-x": SearchXIcon,
	shirt: ShirtIcon,
	"shopping-bag": ShoppingBagIcon,
	soup: SoupIcon,
	sparkles: SparklesIcon,
	tag: TagIcon,
	tags: TagsIcon,
	ticket: TicketIcon,
	toolbox: ToolboxIcon,
	"towel-rack": TowelRackIcon,
	"train-front": TrainFrontIcon,
	trash: TrashIcon,
	"trash-2": Trash2Icon,
	"triangle-alert": TriangleAlertIcon,
	upload: UploadIcon,
	utensils: UtensilsIcon,
	"wallet-cards": WalletCardsIcon,
	warehouse: WarehouseIcon,
	wine: WineIcon,
	wrench: WrenchIcon,
	x: XIcon,
}
