// Bundled Lucide icon map. Every icon renders from the local bundle —
// no runtime CDN fetches, so lists of icons paint in a single pass.
// Unknown names (e.g. hand-typed category icons) fall back to CircleQuestionMark.
import type { LucideIcon } from "lucide-react"
import {
	Apple as AppleIcon,
	ArrowDown as ArrowDownIcon,
	ArrowLeft as ArrowLeftIcon,
	ArrowLeftRight as ArrowLeftRightIcon,
	ArrowRight as ArrowRightIcon,
	ArrowUpRight as ArrowUpRightIcon,
	BadgeDollarSign as BadgeDollarSignIcon,
	Bike as BikeIcon,
	Binoculars as BinocularsIcon,
	BookOpen as BookOpenIcon,
	Brain as BrainIcon,
	CalendarClock as CalendarClockIcon,
	CalendarDays as CalendarDaysIcon,
	Calendar as CalendarIcon,
	CalendarRange as CalendarRangeIcon,
	CardSim as CardSimIcon,
	CarFront as CarFrontIcon,
	CarTaxiFront as CarTaxiFrontIcon,
	ChartArea as ChartAreaIcon,
	ChartCandlestick as ChartCandlestickIcon,
	ChartNoAxesCombined as ChartNoAxesCombinedIcon,
	ChevronDown as ChevronDownIcon,
	ChevronLeft as ChevronLeftIcon,
	ChevronRight as ChevronRightIcon,
	CircleAlert as CircleAlertIcon,
	CircleCheckBig as CircleCheckBigIcon,
	CircleCheck as CircleCheckIcon,
	CircleDashed as CircleDashedIcon,
	CircleDollarSign as CircleDollarSignIcon,
	CircleGauge as CircleGaugeIcon,
	CloudDownload as CloudDownloadIcon,
	CloudUpload as CloudUploadIcon,
	Club as ClubIcon,
	Coffee as CoffeeIcon,
	Cpu as CpuIcon,
	CreditCard as CreditCardIcon,
	CupSoda as CupSodaIcon,
	Database as DatabaseIcon,
	DollarSign as DollarSignIcon,
	Download as DownloadIcon,
	File as FileIcon,
	FileJson as FileJsonIcon,
	Film as FilmIcon,
	Flame as FlameIcon,
	FolderCode as FolderCodeIcon,
	Footprints as FootprintsIcon,
	Gauge as GaugeIcon,
	Gift as GiftIcon,
	Guitar as GuitarIcon,
	HandCoins as HandCoinsIcon,
	Handshake as HandshakeIcon,
	HatGlasses as HatGlassesIcon,
	Heart as HeartIcon,
	HeartPulse as HeartPulseIcon,
	History as HistoryIcon,
	Hospital as HospitalIcon,
	House as HouseIcon,
	IceCreamBowl as IceCreamBowlIcon,
	IdCard as IdCardIcon,
	Import as ImportIcon,
	Inbox as InboxIcon,
	Info as InfoIcon,
	Lamp as LampIcon,
	Landmark as LandmarkIcon,
	Link2 as Link2Icon,
	Link2Off as Link2OffIcon,
	Link as LinkIcon,
	ListFilter as ListFilterIcon,
	ListX as ListXIcon,
	LoaderCircle as LoaderCircleIcon,
	MirrorRound as MirrorRoundIcon,
	MonitorSmartphone as MonitorSmartphoneIcon,
	Navigation as NavigationIcon,
	PartyPopper as PartyPopperIcon,
	Pencil as PencilIcon,
	Percent as PercentIcon,
	PiggyBank as PiggyBankIcon,
	Pill as PillIcon,
	Plane as PlaneIcon,
	Plus as PlusIcon,
	ReceiptCent as ReceiptCentIcon,
	ReceiptEuro as ReceiptEuroIcon,
	Receipt as ReceiptIcon,
	ReceiptIndianRupee as ReceiptIndianRupeeIcon,
	ReceiptJapaneseYen as ReceiptJapaneseYenIcon,
	ReceiptPoundSterling as ReceiptPoundSterlingIcon,
	ReceiptRussianRuble as ReceiptRussianRubleIcon,
	ReceiptSwissFranc as ReceiptSwissFrancIcon,
	ReceiptText as ReceiptTextIcon,
	ReceiptTurkishLira as ReceiptTurkishLiraIcon,
	RefreshCw as RefreshCwIcon,
	Replace as ReplaceIcon,
	RotateCcw as RotateCcwIcon,
	Route as RouteIcon,
	Sandwich as SandwichIcon,
	Scale as ScaleIcon,
	Scissors as ScissorsIcon,
	ScrollText as ScrollTextIcon,
	SearchX as SearchXIcon,
	ShieldCheck as ShieldCheckIcon,
	Shirt as ShirtIcon,
	ShoppingBag as ShoppingBagIcon,
	Soup as SoupIcon,
	Sparkles as SparklesIcon,
	Tag as TagIcon,
	Tags as TagsIcon,
	Ticket as TicketIcon,
	Toolbox as ToolboxIcon,
	TowelRack as TowelRackIcon,
	TrainFront as TrainFrontIcon,
	Trash2 as Trash2Icon,
	Trash as TrashIcon,
	TriangleAlert as TriangleAlertIcon,
	Upload as UploadIcon,
	Utensils as UtensilsIcon,
	WalletCards as WalletCardsIcon,
	Warehouse as WarehouseIcon,
	Wine as WineIcon,
	Wrench as WrenchIcon,
	X as XIcon,
} from "lucide-react"

export const FALLBACK_ICON_NAME = "circle-question-mark"

export const ICONS: Record<string, LucideIcon> = {
	apple: AppleIcon,
	"arrow-down": ArrowDownIcon,
	"arrow-left": ArrowLeftIcon,
	"arrow-left-right": ArrowLeftRightIcon,
	"arrow-right": ArrowRightIcon,
	"arrow-up-right": ArrowUpRightIcon,
	"badge-dollar-sign": BadgeDollarSignIcon,
	bike: BikeIcon,
	binoculars: BinocularsIcon,
	"book-open": BookOpenIcon,
	brain: BrainIcon,
	calendar: CalendarIcon,
	"calendar-clock": CalendarClockIcon,
	"calendar-days": CalendarDaysIcon,
	"calendar-range": CalendarRangeIcon,
	"car-front": CarFrontIcon,
	"car-taxi-front": CarTaxiFrontIcon,
	"card-sim": CardSimIcon,
	"chart-area": ChartAreaIcon,
	"chart-candlestick": ChartCandlestickIcon,
	"chart-no-axes-combined": ChartNoAxesCombinedIcon,
	"chevron-down": ChevronDownIcon,
	"cloud-download": CloudDownloadIcon,
	"cloud-upload": CloudUploadIcon,
	"chevron-left": ChevronLeftIcon,
	"chevron-right": ChevronRightIcon,
	"circle-alert": CircleAlertIcon,
	"circle-check": CircleCheckIcon,
	"circle-check-big": CircleCheckBigIcon,
	"circle-dashed": CircleDashedIcon,
	"circle-dollar-sign": CircleDollarSignIcon,
	"circle-gauge": CircleGaugeIcon,
	club: ClubIcon,
	coffee: CoffeeIcon,
	cpu: CpuIcon,
	"credit-card": CreditCardIcon,
	"cup-soda": CupSodaIcon,
	database: DatabaseIcon,
	"dollar-sign": DollarSignIcon,
	download: DownloadIcon,
	file: FileIcon,
	"file-json": FileJsonIcon,
	film: FilmIcon,
	flame: FlameIcon,
	"folder-code": FolderCodeIcon,
	footprints: FootprintsIcon,
	gauge: GaugeIcon,
	gift: GiftIcon,
	guitar: GuitarIcon,
	"hand-coins": HandCoinsIcon,
	handshake: HandshakeIcon,
	"hat-glasses": HatGlassesIcon,
	heart: HeartIcon,
	"heart-pulse": HeartPulseIcon,
	history: HistoryIcon,
	hospital: HospitalIcon,
	house: HouseIcon,
	"ice-cream-bowl": IceCreamBowlIcon,
	"id-card": IdCardIcon,
	import: ImportIcon,
	inbox: InboxIcon,
	info: InfoIcon,
	lamp: LampIcon,
	landmark: LandmarkIcon,
	link: LinkIcon,
	"link-2": Link2Icon,
	"link-2-off": Link2OffIcon,
	"list-filter": ListFilterIcon,
	"list-filter-x": ListXIcon,
	"loader-circle": LoaderCircleIcon,
	"mirror-round": MirrorRoundIcon,
	"monitor-smartphone": MonitorSmartphoneIcon,
	navigation: NavigationIcon,
	"party-popper": PartyPopperIcon,
	pencil: PencilIcon,
	percent: PercentIcon,
	"piggy-bank": PiggyBankIcon,
	pill: PillIcon,
	plane: PlaneIcon,
	plus: PlusIcon,
	receipt: ReceiptIcon,
	"receipt-cent": ReceiptCentIcon,
	"receipt-euro": ReceiptEuroIcon,
	"receipt-indian-rupee": ReceiptIndianRupeeIcon,
	"receipt-japanese-yen": ReceiptJapaneseYenIcon,
	"receipt-pound-sterling": ReceiptPoundSterlingIcon,
	"receipt-russian-ruble": ReceiptRussianRubleIcon,
	"receipt-swiss-franc": ReceiptSwissFrancIcon,
	"receipt-text": ReceiptTextIcon,
	"receipt-turkish-lira": ReceiptTurkishLiraIcon,
	"refresh-cw": RefreshCwIcon,
	replace: ReplaceIcon,
	"rotate-ccw": RotateCcwIcon,
	route: RouteIcon,
	sandwich: SandwichIcon,
	scale: ScaleIcon,
	scissors: ScissorsIcon,
	"scroll-text": ScrollTextIcon,
	"search-x": SearchXIcon,
	"shield-check": ShieldCheckIcon,
	shirt: ShirtIcon,
	"shopping-bag": ShoppingBagIcon,
	soup: SoupIcon,
	sparkles: SparklesIcon,
	tag: TagIcon,
	tags: TagsIcon,
	ticket: TicketIcon,
	toolbox: ToolboxIcon,
	"towel-rack": TowelRackIcon,
	"train-front": TrainFrontIcon,
	trash: TrashIcon,
	"trash-2": Trash2Icon,
	"triangle-alert": TriangleAlertIcon,
	upload: UploadIcon,
	utensils: UtensilsIcon,
	"wallet-cards": WalletCardsIcon,
	warehouse: WarehouseIcon,
	wine: WineIcon,
	wrench: WrenchIcon,
	x: XIcon,
}
