import type { ForwardRefExoticComponent, RefAttributes, SVGAttributes } from "react"

export type IconNode = [elementName: keyof SVGElementTagNameMap, attrs: Record<string, string>][]
export interface LucideProps extends SVGAttributes<SVGSVGElement> {
	size?: string | number
	absoluteStrokeWidth?: boolean
}
export type LucideIcon = ForwardRefExoticComponent<
	Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>
>

export { default as AppleIcon } from "lucide-react/dist/esm/icons/apple.mjs"
export { default as ArrowLeftIcon } from "lucide-react/dist/esm/icons/arrow-left.mjs"
export { default as ArrowLeftRightIcon } from "lucide-react/dist/esm/icons/arrow-left-right.mjs"
export { default as ArrowRightIcon } from "lucide-react/dist/esm/icons/arrow-right.mjs"
export { default as BikeIcon } from "lucide-react/dist/esm/icons/bike.mjs"
export { default as BookOpenIcon } from "lucide-react/dist/esm/icons/book-open.mjs"
export { default as CalendarIcon } from "lucide-react/dist/esm/icons/calendar.mjs"
export { default as CarTaxiFrontIcon } from "lucide-react/dist/esm/icons/car-taxi-front.mjs"
export { default as CardSimIcon } from "lucide-react/dist/esm/icons/card-sim.mjs"
export { default as ChartAreaIcon } from "lucide-react/dist/esm/icons/chart-area.mjs"
export { default as ChartCandlestickIcon } from "lucide-react/dist/esm/icons/chart-candlestick.mjs"
export { default as CheckIcon } from "lucide-react/dist/esm/icons/check.mjs"
export { default as ChevronDownIcon } from "lucide-react/dist/esm/icons/chevron-down.mjs"
export { default as ChevronLeftIcon } from "lucide-react/dist/esm/icons/chevron-left.mjs"
export { default as ChevronRightIcon } from "lucide-react/dist/esm/icons/chevron-right.mjs"
export { default as ChevronUpIcon } from "lucide-react/dist/esm/icons/chevron-up.mjs"
export { default as CircleCheckIcon } from "lucide-react/dist/esm/icons/circle-check.mjs"
export { default as CircleDollarSignIcon } from "lucide-react/dist/esm/icons/circle-dollar-sign.mjs"
export { default as CircleQuestionMarkIcon } from "lucide-react/dist/esm/icons/circle-question-mark.mjs"
export { default as CoffeeIcon } from "lucide-react/dist/esm/icons/coffee.mjs"
export { default as CpuIcon } from "lucide-react/dist/esm/icons/cpu.mjs"
export { default as CreditCardIcon } from "lucide-react/dist/esm/icons/credit-card.mjs"
export { default as CupSodaIcon } from "lucide-react/dist/esm/icons/cup-soda.mjs"
export { default as DollarSignIcon } from "lucide-react/dist/esm/icons/dollar-sign.mjs"
export { default as MoreHorizontalIcon } from "lucide-react/dist/esm/icons/ellipsis.mjs"
export { default as FileIcon } from "lucide-react/dist/esm/icons/file.mjs"
export { default as FilmIcon } from "lucide-react/dist/esm/icons/film.mjs"
export { default as FolderCodeIcon } from "lucide-react/dist/esm/icons/folder-code.mjs"
export { default as FootprintsIcon } from "lucide-react/dist/esm/icons/footprints.mjs"
export { default as GiftIcon } from "lucide-react/dist/esm/icons/gift.mjs"
export { default as GuitarIcon } from "lucide-react/dist/esm/icons/guitar.mjs"
export { default as HandCoinsIcon } from "lucide-react/dist/esm/icons/hand-coins.mjs"
export { default as HandshakeIcon } from "lucide-react/dist/esm/icons/handshake.mjs"
export { default as HatGlassesIcon } from "lucide-react/dist/esm/icons/hat-glasses.mjs"
export { default as HeartIcon } from "lucide-react/dist/esm/icons/heart.mjs"
export { default as HeartPulseIcon } from "lucide-react/dist/esm/icons/heart-pulse.mjs"
export { default as HospitalIcon } from "lucide-react/dist/esm/icons/hospital.mjs"
export { default as IceCreamBowlIcon } from "lucide-react/dist/esm/icons/ice-cream-bowl.mjs"
export { default as IdCardIcon } from "lucide-react/dist/esm/icons/id-card.mjs"
export { default as ImportIcon } from "lucide-react/dist/esm/icons/import.mjs"
export { default as InfoIcon } from "lucide-react/dist/esm/icons/info.mjs"
export { default as LandmarkIcon } from "lucide-react/dist/esm/icons/landmark.mjs"
export { default as LinkIcon } from "lucide-react/dist/esm/icons/link.mjs"
export { default as Link2Icon } from "lucide-react/dist/esm/icons/link-2.mjs"
export { default as Link2OffIcon } from "lucide-react/dist/esm/icons/link-2-off.mjs"
export { default as ListFilterIcon } from "lucide-react/dist/esm/icons/list-filter.mjs"
export { default as Loader2Icon } from "lucide-react/dist/esm/icons/loader-circle.mjs"
export { default as MirrorRoundIcon } from "lucide-react/dist/esm/icons/mirror-round.mjs"
export { default as MonitorSmartphoneIcon } from "lucide-react/dist/esm/icons/monitor-smartphone.mjs"
export { default as NavigationIcon } from "lucide-react/dist/esm/icons/navigation.mjs"
export { default as OctagonXIcon } from "lucide-react/dist/esm/icons/octagon-x.mjs"
export { default as PanelLeftIcon } from "lucide-react/dist/esm/icons/panel-left.mjs"
export { default as PartyPopperIcon } from "lucide-react/dist/esm/icons/party-popper.mjs"
export { default as PencilIcon } from "lucide-react/dist/esm/icons/pencil.mjs"
export { default as PiggyBankIcon } from "lucide-react/dist/esm/icons/piggy-bank.mjs"
export { default as PlaneIcon } from "lucide-react/dist/esm/icons/plane.mjs"
export { default as PlusIcon } from "lucide-react/dist/esm/icons/plus.mjs"
export { default as ReceiptTextIcon } from "lucide-react/dist/esm/icons/receipt-text.mjs"
export { default as ScissorsIcon } from "lucide-react/dist/esm/icons/scissors.mjs"
export { default as SearchIcon } from "lucide-react/dist/esm/icons/search.mjs"
export { default as ShirtIcon } from "lucide-react/dist/esm/icons/shirt.mjs"
export { default as ShoppingBagIcon } from "lucide-react/dist/esm/icons/shopping-bag.mjs"
export { default as SoupIcon } from "lucide-react/dist/esm/icons/soup.mjs"
export { default as SparklesIcon } from "lucide-react/dist/esm/icons/sparkles.mjs"
export { default as TagIcon } from "lucide-react/dist/esm/icons/tag.mjs"
export { default as TicketIcon } from "lucide-react/dist/esm/icons/ticket.mjs"
export { default as ToolboxIcon } from "lucide-react/dist/esm/icons/toolbox.mjs"
export { default as TrainFrontIcon } from "lucide-react/dist/esm/icons/train-front.mjs"
export { default as TrashIcon } from "lucide-react/dist/esm/icons/trash.mjs"
export { default as Trash2Icon } from "lucide-react/dist/esm/icons/trash-2.mjs"
export { default as TriangleAlertIcon } from "lucide-react/dist/esm/icons/triangle-alert.mjs"
export { default as UtensilsIcon } from "lucide-react/dist/esm/icons/utensils.mjs"
export { default as WarehouseIcon } from "lucide-react/dist/esm/icons/warehouse.mjs"
export { default as WineIcon } from "lucide-react/dist/esm/icons/wine.mjs"
export { default as WrenchIcon } from "lucide-react/dist/esm/icons/wrench.mjs"
export { default as XIcon } from "lucide-react/dist/esm/icons/x.mjs"
